questions =  [
    {"id": 0, "question": "你认为跨性别者是有错误身体的灵魂。", "effects": {"essentialist": 1}},
    {"id": 1, "question": "你认为你的性别妨碍了自我实现。", "effects": {"positive": -1}},
    {"id": 2, "question": "你认为男性可以有阴道。", "effects": {"rigid": -1}},
    {"id": 3, "question": "你认为如果所有关于性别的讨论完全消失，社会将变得更好。", "effects": {"positive": -1}},
    {"id": 4, "question": "你认为圣女贞德这样不符合当时性别规范的人可以被视为跨性别。", "effects": {"rigid": -1}},
    {"id": 5, "question": "你认为个人的性别应该由法律明确规定。", "effects": {"rigid": 1}},
    {"id": 6, "question": "你认为跨性别认同形成可能与成长中的经历有关。", "effects": {"essentialist": -1}},
    {"id": 7, "question": "你认为人造子宫和体外生育的实现会导致性别的消失。", "effects": {"essentialist": -1, "rigid": -1}},
    {"id": 8, "question": "你认为古代人会无法理解现在的性别观念。", "effects": {"essentialist": -1}},
    {"id": 9, "question": "你认为跨性别者接受的医学干预是使身体符合他们性别的必要手段。", "effects": {"essentialist": 1, "rigid": -1}},
    {"id": 10, "question": "你认为多元性别观念是当代西方文化影响的产物。", "effects": {"rigid": 1}},
    {"id": 11, "question": "你认为温柔与爱是女性化的特质。", "effects": {"essentialist": 1, "positive": 1}},
    {"id": 12, "question": "你认为没有性别刻板印象就不会有跨性别者。", "effects": {"essentialist": -1, "rigid": 1}},
    {"id": 13, "question": "你认为白幼瘦这样的审美观念是有害的。", "effects": {"positive": -1}},
    {"id": 14, "question": "你认为男性应该承担父亲的职责。", "effects": {"positive": 1}},
    {"id": 15, "question": "你认为一个人真正的性别生来便不会改变。", "effects":  {"essentialist": 1}},
    {"id": 16, "question": "你认为化妆和医美产业与女性的紧密联系是不好的。", "effects": {"positive": -1}},
    {"id": 17, "question": "你认为有些前现代社会的性别制度比现代社会更多元和包容。", "effects": {"rigid": -1 }},
    {"id": 18, "question": "你相信男女的大脑结构不同导致了不同的行为模式。", "effects": {"essentialist": 1}},
    {"id": 19, "question": "你认为异装和跨性别只是程度差别。", "effects":  {"essentialist": -1, "rigid": -1}},
    {"id": 20, "question": "你认为女性总是更容易找到伴侣。", "effects":  {"essentialist": 1}},
];
